// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }






// // App/layout.tsx
// import React from "react"
// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
// // import { Analytics } from '@vercel/analytics/next'
// import { ThemeProvider } from '@/components/theme-provider'
// import './globals.css'
// import { Header } from "@/components/shared/header"
// import { Footer } from "@/components/shared/footer"

// const _geist = Geist({ subsets: ["latin"] });
// const _geistMono = Geist_Mono({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Chronify AI - AI-Powered Student Productivity',
//   description: 'Plan smart, study consistent, and succeed faster with AI-powered time management for students.',
//   generator: 'v0.app',
//   icons: {
//     icon: [
//       {
//         url: '/icon-light-32x32.png',
//         media: '(prefers-color-scheme: light)',
//       },
//       {
//         url: '/icon-dark-32x32.png',
//         media: '(prefers-color-scheme: dark)',
//       },
//       {
//         url: '/icon.svg',
//         type: 'image/svg+xml',
//       },
//     ],
//     apple: '/apple-icon.png',
//   },
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning className="dark">
//       <body className={`font-sans antialiased bg-background text-foreground transition-colors duration-300`}>
//         <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange={false} storageKey="studyflow-theme" forcedTheme={undefined}>
//           <Header/>
//           {children}
//           <Footer/>
//         </ThemeProvider>
//         {/* <Analytics /> */}
//       </body>
//     </html>
//   )
// }
















// src/app/layout.tsx
import React from "react"
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import { Header } from "@/components/shared/header"
import { Footer } from "@/components/shared/footer"
import { TutorialTourProvider } from '@/contexts/tutorial-tour-context'
import FCMProvider from "@/components/shared/FCMProvider"

const geist = Geist({ subsets: ["latin"] });
const geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Chronify AI - AI-Powered Student Productivity',
  description: 'Plan smart, study consistent, and succeed faster with AI-powered time management for students.',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geist.className} antialiased bg-background text-foreground`}>
        <TutorialTourProvider>
          <ThemeProvider 
            attribute="class" 
            defaultTheme="dark" 
            enableSystem 
            disableTransitionOnChange
            storageKey="studyflow-theme"
          >
            <Header/>
            <FCMProvider />
            {children}
            <Footer/>
          </ThemeProvider>
        </TutorialTourProvider>
      </body>
    </html>
  )
}